package net.sf.kernow.ui;

import javax.swing.table.DefaultTableModel;
import net.sf.kernow.Config;
import net.sf.kernow.xquery.NamespaceBindings;

/**
 * Dialog box to set bindings on a NamespaceBindings object.
 *
 * @author Florent Georges
 */
public class NamespacesDiag extends javax.swing.JFrame {
    
    private Config config;
    private NamespaceBindings nsBindings;
    
    /**
     * Construct a new box to edit {@code bindings}, and initialise the values on the table from it.
     */
    public NamespacesDiag(NamespaceBindings bindings) {
        config = config.getConfig();        
        initComponents();
    }
    
    /* Populates the table with the bindings stored in the config */
    private void initTable() {
        
        DefaultTableModel model = ((DefaultTableModel) bindingTable.getModel());
        nsBindings = config.getNamespaceBindings();
        
        // remove all rows
        model.setRowCount(0);
        
        // add each binding
        for (String prefix : nsBindings.getPrefixes()) {
            String[] row = new String[]{ prefix, nsBindings.getBinding(prefix) };
            model.addRow(row);            
        }                
    }
    
    /* Re-populates the table and shows the dialog.  It does this each time to
     * allow the user to click the X to discard the changes, and click "save and
     * close" to keep the changes. */
    public void showDiag() {
        initTable();
        this.setVisible(true);
    }
    
    /**
     * Remove the selected binding row, defaulted to the last one.
     */
    private void removeRow() {
        int index = bindingTable.getSelectedRow();
        if (index == -1) {
            index = bindingTable.getRowCount() - 1;
        }
        if (index >= 0) {                        
            ((DefaultTableModel) bindingTable.getModel()).removeRow(index);
        }                
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        titleLbl = new javax.swing.JLabel();
        titleSeparator = new javax.swing.JSeparator();
        bindingTableScroll = new javax.swing.JScrollPane();
        bindingTable = new javax.swing.JTable();
        closeDialogBtn = new javax.swing.JButton();
        deleteBindingBtn = new javax.swing.JButton();
        addBindingBtn = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/NamespacesDiag"); // NOI18N
        setTitle(bundle.getString("Namespace_Bindings_for_the_XQuery_Sandbox")); // NOI18N
        titleLbl.setFont(new java.awt.Font("Arial", 1, 12));
        titleLbl.setText(bundle.getString("Namespace_bindings")); // NOI18N

        bindingTable.setFont(new java.awt.Font("Arial", 0, 12));
        bindingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Prefix", "URI"
            }
        ));
        bindingTableScroll.setViewportView(bindingTable);

        closeDialogBtn.setText(bundle.getString("Save_and_Close")); // NOI18N
        closeDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeDialogBtnActionPerformed(evt);
            }
        });

        deleteBindingBtn.setText(bundle.getString("Delete_Binding")); // NOI18N
        deleteBindingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBindingBtnActionPerformed(evt);
            }
        });

        addBindingBtn.setText(bundle.getString("Add_Binding")); // NOI18N
        addBindingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBindingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bindingTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(titleSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(titleLbl)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addBindingBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBindingBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeDialogBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bindingTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeDialogBtn)
                    .addComponent(deleteBindingBtn)
                    .addComponent(addBindingBtn))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void addBindingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBindingBtnActionPerformed
        ((DefaultTableModel) bindingTable.getModel()).addRow(new Object[]{ null, null });
    }//GEN-LAST:event_addBindingBtnActionPerformed
    
private void deleteBindingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBindingBtnActionPerformed
    removeRow();
}//GEN-LAST:event_deleteBindingBtnActionPerformed

private void closeDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeDialogBtnActionPerformed
    
    // first clear all existing bindings in the config
    nsBindings.removeAllBindings();
    int row = -1;
    try {
        // then add the bindings in the table
        for ( int i = 0; i < bindingTable.getRowCount(); i++) {
            row = i;
            String prefix = (String) bindingTable.getValueAt(i, 0);
            String uri    = (String) bindingTable.getValueAt(i, 1);
            if ( prefix != null && uri != null ) {
                nsBindings.addBinding(prefix, uri);
            }
        }
        
        setVisible(false);
    } catch (IllegalArgumentException ex) {
        System.err.println(java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/NamespacesDiag").getString("Error!_The_prefix_in_row_") + ++row + java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/NamespacesDiag").getString("_is_already_defined"));
    } catch (NullPointerException ex) {
        System.err.println(java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/NamespacesDiag").getString("Error!_The_prefix_or_namespace_URI_in_row_") + ++row + java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/NamespacesDiag").getString("_is_empty"));
    }  
}//GEN-LAST:event_closeDialogBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBindingBtn;
    private javax.swing.JTable bindingTable;
    private javax.swing.JScrollPane bindingTableScroll;
    private javax.swing.JButton closeDialogBtn;
    private javax.swing.JButton deleteBindingBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JSeparator titleSeparator;
    // End of variables declaration//GEN-END:variables
}
