/*
 * Saxonica.java
 *
 * Created on 25 January 2008, 15:26
 */

package net.sf.kernow.ui;

import java.awt.Cursor;
import java.awt.Toolkit;
import net.sf.kernow.util.BrowserLauncher;

/**
 *
 * @author  awelch
 */
public class Saxonica extends javax.swing.JFrame {
    
    /** Creates new form Saxonica */
    public Saxonica() {
        initComponents();
        
        MouseListener mouseListener = new MouseListener(this, Cursor.HAND_CURSOR);
        
        saxonicaLogo.addMouseMotionListener(mouseListener);
        saxonicaClickHereLbl.addMouseMotionListener(mouseListener);    
        
        MouseListener generalMouseListener = new MouseListener(this, Cursor.DEFAULT_CURSOR);
        super.addMouseMotionListener(generalMouseListener);  
        
        // set the dialog icon
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage(this.getClass().getClassLoader().getResource("icons/Kernow-Icon.gif")));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saxonicaLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saxonicaClickHereLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        schemaAwareLbl = new javax.swing.JLabel();
        saxonicaCloseBttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/SaxonicaTrial"); // NOI18N
        setTitle(bundle.getString("Saxonica.title")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Saxonica.jPanel1.border.title"))); // NOI18N

        saxonicaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saxonica/saxonica_logo.gif"))); // NOI18N
        saxonicaLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saxonicaLogoMouseClicked(evt);
            }
        });

        jLabel2.setText(bundle.getString("Saxonica.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText(bundle.getString("Saxonica.jLabel3.text")); // NOI18N

        saxonicaClickHereLbl.setForeground(new java.awt.Color(0, 0, 255));
        saxonicaClickHereLbl.setText(bundle.getString("Saxonica.saxonicaClickHereLbl.text")); // NOI18N
        saxonicaClickHereLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saxonicaClickHereLblMouseClicked(evt);
            }
        });

        jLabel6.setText(bundle.getString("Saxonica.jLabel6.text")); // NOI18N

        schemaAwareLbl.setForeground(new java.awt.Color(0, 0, 255));
        schemaAwareLbl.setText(bundle.getString("Saxonica.schemaAwareLbl.text")); // NOI18N
        schemaAwareLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schemaAwareLblMouseClicked(evt);
            }
        });

        saxonicaCloseBttn.setText(bundle.getString("Saxonica.saxonicaCloseBttn.text")); // NOI18N
        saxonicaCloseBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saxonicaCloseBttnActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("Saxonica.jLabel1.text")); // NOI18N

        jLabel5.setText(bundle.getString("Saxonica.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(saxonicaCloseBttn)
                        .addComponent(saxonicaLogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schemaAwareLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saxonicaClickHereLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saxonicaLogo)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saxonicaClickHereLbl)
                        .addComponent(jLabel6)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(schemaAwareLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(saxonicaCloseBttn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saxonicaCloseBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saxonicaCloseBttnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_saxonicaCloseBttnActionPerformed

    private void saxonicaClickHereLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saxonicaClickHereLblMouseClicked
        BrowserLauncher.openURL("http://andrewjwelch.com/saxon");
    }//GEN-LAST:event_saxonicaClickHereLblMouseClicked

    private void schemaAwareLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schemaAwareLblMouseClicked
        BrowserLauncher.openURL("http://schema-aware.com/");
    }//GEN-LAST:event_schemaAwareLblMouseClicked

    private void saxonicaLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saxonicaLogoMouseClicked
        BrowserLauncher.openURL("http://andrewjwelch.com/saxon");
    }//GEN-LAST:event_saxonicaLogoMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saxonica().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel saxonicaClickHereLbl;
    private javax.swing.JButton saxonicaCloseBttn;
    private javax.swing.JLabel saxonicaLogo;
    private javax.swing.JLabel schemaAwareLbl;
    // End of variables declaration//GEN-END:variables
    
}
