/*
 * Options.java
 *
 * Created on 30th November 2005
 */

package net.sf.kernow.ui;

import net.sf.kernow.Config;

/**
 *
 * @author  AWelch
 */
public class SchemaAwareDiag extends javax.swing.JFrame {
    
    Config config;
    
    /** Creates new form Options */
    public SchemaAwareDiag() {

        this.config = Config.getConfig();
        
        // Set the opening location of the window
        super.setLocation(50, 50);
        
        initComponents();
        
        schemaAwareValidationButtonGroup.add(skipValidationRadioButton);
        schemaAwareValidationButtonGroup.add(laxValidationRadioButton);
        schemaAwareValidationButtonGroup.add(strictValidationRadioButton);       
               
        loadOptionsFromConfig();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schemaAwareValidationButtonGroup = new javax.swing.ButtonGroup();
        validationButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        doneBtn = new javax.swing.JButton();
        schemaAwareTabbedPane = new javax.swing.JTabbedPane();
        optionsSchemaAwarePanel = new javax.swing.JPanel();
        useSchemaAwareChkBox = new javax.swing.JCheckBox();
        skipValidationRadioButton = new javax.swing.JRadioButton();
        laxValidationRadioButton = new javax.swing.JRadioButton();
        strictValidationRadioButton = new javax.swing.JRadioButton();
        vwChkBx = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/SchemaAwareDiag"); // NOI18N
        setTitle(bundle.getString("Configure_Schema_Aware")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("SchemaAwareDiag.jPanel1.border.title"))); // NOI18N

        doneBtn.setText(bundle.getString("Done")); // NOI18N
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        useSchemaAwareChkBox.setText(bundle.getString("Use_Schema_Aware_Saxon")); // NOI18N
        useSchemaAwareChkBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useSchemaAwareChkBox.setEnabled(false);
        useSchemaAwareChkBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useSchemaAwareChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSchemaAwareChkBoxActionPerformed(evt);
            }
        });

        skipValidationRadioButton.setText(bundle.getString("Skip_validation")); // NOI18N
        skipValidationRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        skipValidationRadioButton.setEnabled(false);
        skipValidationRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        skipValidationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipValidationRadioButtonActionPerformed(evt);
            }
        });

        laxValidationRadioButton.setText(bundle.getString("Lax_validation")); // NOI18N
        laxValidationRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        laxValidationRadioButton.setEnabled(false);
        laxValidationRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        laxValidationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laxValidationRadioButtonActionPerformed(evt);
            }
        });

        strictValidationRadioButton.setSelected(true);
        strictValidationRadioButton.setText(bundle.getString("Strict_validation")); // NOI18N
        strictValidationRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        strictValidationRadioButton.setEnabled(false);
        strictValidationRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        strictValidationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strictValidationRadioButtonActionPerformed(evt);
            }
        });

        vwChkBx.setSelected(true);
        vwChkBx.setText(bundle.getString("Treat_fatal_validation_errors_as_warnings")); // NOI18N
        vwChkBx.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        vwChkBx.setEnabled(false);
        vwChkBx.setMargin(new java.awt.Insets(0, 0, 0, 0));
        vwChkBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vwChkBxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText(bundle.getString("Source_document_validation")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel2.setText(bundle.getString("(enabled_by_default_when_SaxonSA_is_detected,_uncheck_to_use_Saxon_Basic)")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel3.setText(bundle.getString("(don't_validate_source_documents)")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel4.setText(bundle.getString("(validate_source_documents_if_a_definition_is_found)")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel5.setText(bundle.getString("(validate_source_documents)")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel6.setText(bundle.getString("(validation_errors_are_reported_after_processing_has_completed)")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText(bundle.getString("Result_document_validation")); // NOI18N

        org.jdesktop.layout.GroupLayout optionsSchemaAwarePanelLayout = new org.jdesktop.layout.GroupLayout(optionsSchemaAwarePanel);
        optionsSchemaAwarePanel.setLayout(optionsSchemaAwarePanelLayout);
        optionsSchemaAwarePanelLayout.setHorizontalGroup(
            optionsSchemaAwarePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(optionsSchemaAwarePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(useSchemaAwareChkBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(305, 305, 305))
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(jLabel2)
                        .addContainerGap(80, Short.MAX_VALUE))
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap(290, Short.MAX_VALUE))
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(skipValidationRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)
                        .addContainerGap(196, Short.MAX_VALUE))
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(laxValidationRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(strictValidationRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)
                        .addContainerGap(217, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(vwChkBx)
                        .addContainerGap(239, Short.MAX_VALUE))
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(jLabel6)
                        .addContainerGap(145, Short.MAX_VALUE))
                    .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                        .add(jLabel7)
                        .addContainerGap(293, Short.MAX_VALUE))))
        );
        optionsSchemaAwarePanelLayout.setVerticalGroup(
            optionsSchemaAwarePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(optionsSchemaAwarePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(useSchemaAwareChkBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(optionsSchemaAwarePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(skipValidationRadioButton)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(optionsSchemaAwarePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(laxValidationRadioButton)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(optionsSchemaAwarePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(strictValidationRadioButton)
                    .add(jLabel5))
                .add(15, 15, 15)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(vwChkBx)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        schemaAwareTabbedPane.addTab(bundle.getString("Schema_Aware"), optionsSchemaAwarePanel); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, schemaAwareTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .add(doneBtn))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(schemaAwareTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(doneBtn))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vwChkBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vwChkBxActionPerformed
        config.setTreatValidationErrorsAsWarnings(vwChkBx.isSelected());
    }//GEN-LAST:event_vwChkBxActionPerformed

    private void strictValidationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strictValidationRadioButtonActionPerformed
        setValidationSwitch();
    }//GEN-LAST:event_strictValidationRadioButtonActionPerformed

    private void laxValidationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laxValidationRadioButtonActionPerformed
        setValidationSwitch();
    }//GEN-LAST:event_laxValidationRadioButtonActionPerformed

    private void skipValidationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipValidationRadioButtonActionPerformed
        setValidationSwitch();
    }//GEN-LAST:event_skipValidationRadioButtonActionPerformed
    
    private void setValidationSwitch() {
        config.setStrictValidation(strictValidationRadioButton.isSelected());
        config.setLaxValidation(laxValidationRadioButton.isSelected());
        config.setSkipValidation(skipValidationRadioButton.isSelected());
    }
    
    private void toggleSchemaAwareOptions(boolean enable) {
        skipValidationRadioButton.setEnabled(enable);            
        laxValidationRadioButton.setEnabled(enable);
        strictValidationRadioButton.setEnabled(enable);
        vwChkBx.setEnabled(enable);    
        config.setUseSchemaAware(enable);
    }
           
    public void loadOptionsFromConfig() {
        useSchemaAwareChkBox.setEnabled(config.isSchemaAwareEnabled());      
        toggleSchemaAwareOptions(config.isSchemaAwareEnabled());
        useSchemaAwareChkBox.setSelected(config.isSchemaAwareEnabled());  
        
        skipValidationRadioButton.setSelected(config.isSkipValidation());
        laxValidationRadioButton.setSelected(config.isLaxValidation());
        strictValidationRadioButton.setSelected(config.isStrictValidation());
        
        vwChkBx.setSelected(config.isTreatValidationErrorsAsWarnings());
        
        setValidationSwitch();
    }
    
    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_doneBtnActionPerformed

    private void useSchemaAwareChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSchemaAwareChkBoxActionPerformed
        toggleSchemaAwareOptions(useSchemaAwareChkBox.isSelected());        
    }//GEN-LAST:event_useSchemaAwareChkBoxActionPerformed
   
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton laxValidationRadioButton;
    private javax.swing.JPanel optionsSchemaAwarePanel;
    private javax.swing.JTabbedPane schemaAwareTabbedPane;
    private javax.swing.ButtonGroup schemaAwareValidationButtonGroup;
    private javax.swing.JRadioButton skipValidationRadioButton;
    private javax.swing.JRadioButton strictValidationRadioButton;
    private javax.swing.JCheckBox useSchemaAwareChkBox;
    private javax.swing.ButtonGroup validationButtonGroup;
    private javax.swing.JCheckBox vwChkBx;
    // End of variables declaration//GEN-END:variables
    
}
