/*
 * Switches.java
 *
 * Created on 06 November 2005, 18:50
 */

package net.sf.kernow.ui;

import java.awt.Toolkit;
import net.sf.kernow.Config;

/**
 * UI for setting the various command line switches for Saxon
 * @author  AWelch
 */
public class Switches extends javax.swing.JFrame {
    
    private Config config;
    
    /** Creates new form Switches */
    public Switches() {
        // Set the opening location of the window
        super.setLocation(50, 50);
        
        config = Config.getConfig();
        
        initComponents();        
        
        // set the dialog icon
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage(this.getClass().getClassLoader().getResource("icons/Kernow-Icon.gif")));
        
        // Sort out the radio button groups
        // First the tree types
        treeTypeButtonGroup.add(radioButtonDS);
        treeTypeButtonGroup.add(radioButtonDT);
        
        // Now the whitespace
        whitespaceButtonGroup.add(radioButtonSALL);
        whitespaceButtonGroup.add(radioButtonSIGNORABLE);
        whitespaceButtonGroup.add(radioButtonSNONE);
        
        // Now the warnings
        warningsButtonGroup.add(radioButtonW0);
        warningsButtonGroup.add(radioButtonW1);
        warningsButtonGroup.add(radioButtonW2);
    
        loadSettings();
    }
   
    void loadSettings() {
        radioButtonDS.setSelected(config.isUseStandardTree());
        radioButtonDT.setSelected(config.isUseTinyTree());

        chkBxExplain.setSelected(config.isExplain());
        
        chkBoxIM.setSelected(config.isUseInitialMode());
        initialModeTextField.setEnabled(config.isUseInitialMode());
        initialModeTextField.setText(config.getInitialMode());

        chkBoxIT.setSelected(config.isUseInitialTemplate());
        initialTemplateTextField.setEnabled(config.isUseInitialTemplate());
        initialTemplateTextField.setText(config.getInitialTemplate());

        chkBoxL.setSelected(config.isRetainLineNumbers());
        chkBoxNOVW.setSelected(config.isNovw());

        radioButtonSALL.setSelected(config.isStripAllWhitespace());
        radioButtonSIGNORABLE.setSelected(config.isStripIgnorableWhitespace());
        radioButtonSNONE.setSelected(config.isStripNoWhitespace());

        chkBoxT.setSelected(config.isShowTiming());
        chkBoxTraceJava.setSelected(config.isTraceCalls());

        radioButtonW0.setSelected(config.isRecoverablesAreSilent());
        radioButtonW1.setSelected(config.isRecoverablesAreReported());
        radioButtonW2.setSelected(config.isRecoverablesAreFatal());

        chkBox1point1.setSelected(config.isAllowXML11());            
    }     
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeTypeButtonGroup = new javax.swing.ButtonGroup();
        whitespaceButtonGroup = new javax.swing.ButtonGroup();
        warningsButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkBoxIM = new javax.swing.JCheckBox();
        initialModeTextField = new javax.swing.JTextField();
        chkBoxL = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        chkBoxNOVW = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        chkBoxT = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        chkBox1point1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        chkBoxIT = new javax.swing.JCheckBox();
        initialTemplateTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chkBoxTraceJava = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        radioButtonDS = new javax.swing.JRadioButton();
        radioButtonDT = new javax.swing.JRadioButton();
        radioButtonSALL = new javax.swing.JRadioButton();
        radioButtonSIGNORABLE = new javax.swing.JRadioButton();
        radioButtonSNONE = new javax.swing.JRadioButton();
        radioButtonW0 = new javax.swing.JRadioButton();
        radioButtonW1 = new javax.swing.JRadioButton();
        radioButtonW2 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        chkBxExplain = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        doneBtn = new javax.swing.JButton();
        switchesRestoreDefaultsBtn = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/Switches"); // NOI18N
        setTitle(bundle.getString("Switches")); // NOI18N
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel4.setText("-ds");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setText("-dt");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel6.setText("-im");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel7.setText("-l");

        chkBoxIM.setFont(new java.awt.Font("Arial", 0, 11));
        chkBoxIM.setText(bundle.getString("Start_transformation_in_specified_mode")); // NOI18N
        chkBoxIM.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoxIM.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkBoxIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxIMActionPerformed(evt);
            }
        });

        initialModeTextField.setFont(new java.awt.Font("Arial", 0, 11));
        initialModeTextField.setText(bundle.getString("_[initial_mode]")); // NOI18N
        initialModeTextField.setEnabled(false);

        chkBoxL.setFont(new java.awt.Font("Arial", 0, 11));
        chkBoxL.setText(bundle.getString("Retain_line_numbers_in_source_document_tree")); // NOI18N
        chkBoxL.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoxL.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkBoxL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxLActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setText("-novw");

        chkBoxNOVW.setFont(new java.awt.Font("Arial", 0, 11));
        chkBoxNOVW.setText(bundle.getString("Suppress_warning_when_using_an_XSLT_1.0_stylesheet")); // NOI18N
        chkBoxNOVW.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoxNOVW.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkBoxNOVW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxNOVWActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setText("-t");

        chkBoxT.setFont(new java.awt.Font("Arial", 0, 11));
        chkBoxT.setText(bundle.getString("Display_version_and_timing_information")); // NOI18N
        chkBoxT.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoxT.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkBoxT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxTActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel8.setText("-1.1");

        chkBox1point1.setFont(new java.awt.Font("Arial", 0, 11));
        chkBox1point1.setText(bundle.getString("Allow_XML_1.1_documents")); // NOI18N
        chkBox1point1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBox1point1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkBox1point1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBox1point1ActionPerformed(evt);
            }
        });

        jLabel13.setText("-it");

        chkBoxIT.setText(bundle.getString("Start_transformation_by_calling_named_template")); // NOI18N
        chkBoxIT.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoxIT.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkBoxIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxITActionPerformed(evt);
            }
        });

        initialTemplateTextField.setText(bundle.getString("[initial_template]")); // NOI18N
        initialTemplateTextField.setEnabled(false);

        jLabel16.setText("-sall");

        jLabel17.setText("-signorable");

        jLabel18.setText("-snone");

        jLabel19.setText("-TJ");

        chkBoxTraceJava.setText(bundle.getString("Trace_calls_to_external_Java_functions")); // NOI18N
        chkBoxTraceJava.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkBoxTraceJava.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkBoxTraceJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxTraceJavaActionPerformed(evt);
            }
        });

        jLabel23.setText("-w0");

        jLabel24.setText("-w1");

        jLabel25.setText("-w2");

        radioButtonDS.setText(bundle.getString("Use_standard_tree_data_structure")); // NOI18N
        radioButtonDS.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonDS.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonDSActionPerformed(evt);
            }
        });

        radioButtonDT.setSelected(true);
        radioButtonDT.setText(bundle.getString("Use_tinytree_data_structure_(default)")); // NOI18N
        radioButtonDT.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonDT.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonDTActionPerformed(evt);
            }
        });

        radioButtonSALL.setText(bundle.getString("Strip_all_whitespace_text_nodes")); // NOI18N
        radioButtonSALL.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonSALL.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonSALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSALLActionPerformed(evt);
            }
        });

        radioButtonSIGNORABLE.setSelected(true);
        radioButtonSIGNORABLE.setText(bundle.getString("Strip_ignorable_whitespace_text_nodes")); // NOI18N
        radioButtonSIGNORABLE.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonSIGNORABLE.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonSIGNORABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSIGNORABLEActionPerformed(evt);
            }
        });

        radioButtonSNONE.setText(bundle.getString("Strip_no_whitespace_text_nodes_(default)")); // NOI18N
        radioButtonSNONE.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonSNONE.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonSNONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSNONEActionPerformed(evt);
            }
        });

        radioButtonW0.setText(bundle.getString("Recover_silently_from_recoverable_errors")); // NOI18N
        radioButtonW0.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonW0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonW0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonW0ActionPerformed(evt);
            }
        });

        radioButtonW1.setSelected(true);
        radioButtonW1.setText(bundle.getString("Report_recoverable_errors_and_continue_(default)")); // NOI18N
        radioButtonW1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonW1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonW1ActionPerformed(evt);
            }
        });

        radioButtonW2.setText(bundle.getString("Treat_recoverable_errors_as_fatal")); // NOI18N
        radioButtonW2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonW2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonW2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText(bundle.getString("XSLT_Specific_options")); // NOI18N

        chkBxExplain.setText("Explain");
        chkBxExplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBxExplainActionPerformed(evt);
            }
        });

        jLabel10.setText("-explain");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(41, 41, 41)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(radioButtonDS)
                            .add(radioButtonDT)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jLabel16)
                            .add(jLabel17)
                            .add(jLabel18)
                            .add(jLabel2)
                            .add(jLabel19)
                            .add(jLabel23)
                            .add(jLabel24)
                            .add(jLabel25)
                            .add(jLabel8)
                            .add(jLabel10))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(chkBoxL)
                            .add(radioButtonSNONE)
                            .add(radioButtonSIGNORABLE)
                            .add(chkBoxT)
                            .add(radioButtonSALL)
                            .add(chkBoxTraceJava)
                            .add(radioButtonW0)
                            .add(radioButtonW1)
                            .add(radioButtonW2)
                            .add(chkBox1point1)
                            .add(chkBxExplain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel3)
                    .add(jLabel6)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel13)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(initialTemplateTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(chkBoxIT)
                            .add(initialModeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(chkBoxIM)
                            .add(chkBoxNOVW))))
                .addContainerGap(44, Short.MAX_VALUE))
            .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(radioButtonDS))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(radioButtonDT))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(chkBxExplain))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(chkBoxL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(radioButtonSALL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(radioButtonSIGNORABLE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18)
                    .add(radioButtonSNONE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(chkBoxT))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel19)
                    .add(chkBoxTraceJava))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel23)
                    .add(radioButtonW0))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel24)
                    .add(radioButtonW1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel25)
                    .add(radioButtonW2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(chkBox1point1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(chkBoxIM))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(initialModeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(chkBoxIT))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(initialTemplateTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(chkBoxNOVW))
                .add(38, 38, 38))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText(bundle.getString("Command_Line_Switches")); // NOI18N

        doneBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        doneBtn.setText(bundle.getString("Done")); // NOI18N
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        switchesRestoreDefaultsBtn.setText(bundle.getString("Restore_Defaults")); // NOI18N
        switchesRestoreDefaultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchesRestoreDefaultsBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel9)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(switchesRestoreDefaultsBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 124, Short.MAX_VALUE)
                        .add(doneBtn)
                        .add(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(doneBtn)
                    .add(switchesRestoreDefaultsBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBoxNOVWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxNOVWActionPerformed
        config.setNovw(chkBoxNOVW.isSelected());
    }//GEN-LAST:event_chkBoxNOVWActionPerformed

    private void radioButtonW0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonW0ActionPerformed
        config.setRecoverablesAreSilent(radioButtonW0.isSelected());
        config.setRecoverablesAreReported(radioButtonW1.isSelected());
        config.setRecoverablesAreFatal(radioButtonW2.isSelected());
    }//GEN-LAST:event_radioButtonW0ActionPerformed

    private void radioButtonW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonW1ActionPerformed
        config.setRecoverablesAreSilent(radioButtonW0.isSelected());
        config.setRecoverablesAreReported(radioButtonW1.isSelected());
        config.setRecoverablesAreFatal(radioButtonW2.isSelected());
    }//GEN-LAST:event_radioButtonW1ActionPerformed

    private void radioButtonW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonW2ActionPerformed
        config.setRecoverablesAreSilent(radioButtonW0.isSelected());        
        config.setRecoverablesAreReported(radioButtonW1.isSelected());
        config.setRecoverablesAreFatal(radioButtonW2.isSelected());
    }//GEN-LAST:event_radioButtonW2ActionPerformed

    
    
    private void radioButtonSNONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSNONEActionPerformed
        setWhitespaceHandling();
    }//GEN-LAST:event_radioButtonSNONEActionPerformed

    private void radioButtonSIGNORABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSIGNORABLEActionPerformed
        setWhitespaceHandling();
    }//GEN-LAST:event_radioButtonSIGNORABLEActionPerformed

    private void radioButtonSALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSALLActionPerformed
        setWhitespaceHandling();
    }//GEN-LAST:event_radioButtonSALLActionPerformed

    private void setWhitespaceHandling() {
        config.setStripNoWhitespace(radioButtonSNONE.isSelected());        
        config.setStripIgnorableWhitespace(radioButtonSIGNORABLE.isSelected());
        config.setStripAllWhitespace(radioButtonSALL.isSelected());           
    }
    
    private void radioButtonDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonDTActionPerformed
        config.setUseTinyTree(radioButtonDT.isSelected());
    }//GEN-LAST:event_radioButtonDTActionPerformed

    private void radioButtonDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonDSActionPerformed
        config.setUseStandardTree(radioButtonDS.isSelected());
    }//GEN-LAST:event_radioButtonDSActionPerformed

    private void chkBox1point1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBox1point1ActionPerformed
        config.setAllowXML11(chkBox1point1.isSelected());
    }//GEN-LAST:event_chkBox1point1ActionPerformed

    private void chkBoxTraceJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxTraceJavaActionPerformed
        config.setTraceCalls(chkBoxTraceJava.isSelected());
    }//GEN-LAST:event_chkBoxTraceJavaActionPerformed

    private void chkBoxTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxTActionPerformed
        config.setShowTiming(chkBoxT.isSelected());
    }//GEN-LAST:event_chkBoxTActionPerformed

    private void chkBoxLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxLActionPerformed
        config.setRetainLineNumbers(chkBoxL.isSelected());
    }//GEN-LAST:event_chkBoxLActionPerformed

    private void switchesRestoreDefaultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchesRestoreDefaultsBtnActionPerformed
        radioButtonDT.setSelected(true);
        
        chkBxExplain.setSelected(false);
        
        chkBoxIM.setSelected(false);
        initialModeTextField.setText(java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/Switches").getString("[initial_mode]"));
        initialModeTextField.setEnabled(false);
        
        chkBoxIT.setSelected(false);
        initialTemplateTextField.setText(java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/Switches").getString("[initial_template]"));
        initialTemplateTextField.setEnabled(false);
                               
        chkBoxL.setSelected(false);
        chkBoxNOVW.setSelected(false);
        
        radioButtonSNONE.setSelected(true);
        
        chkBoxT.setSelected(false);
        chkBoxTraceJava.setSelected(false);
        
        radioButtonW1.setSelected(true);

        chkBox1point1.setSelected(false);                
    }//GEN-LAST:event_switchesRestoreDefaultsBtnActionPerformed
   
    private void saveValuesToConfig() {
        config.setInitialMode(initialModeTextField.getText());
        config.setInitialTemplate(initialTemplateTextField.getText());
    }
    
    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        saveValuesToConfig();
        setVisible(false);
    }//GEN-LAST:event_doneBtnActionPerformed

    private void chkBoxITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxITActionPerformed
        config.setUseInitialTemplate(chkBoxIT.isSelected());
        initialTemplateTextField.setEnabled(chkBoxIT.isSelected());
    }//GEN-LAST:event_chkBoxITActionPerformed

    private void chkBoxIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxIMActionPerformed
        config.setUseInitialMode(chkBoxIM.isSelected());
        initialModeTextField.setEnabled(chkBoxIM.isSelected());
    }//GEN-LAST:event_chkBoxIMActionPerformed

private void chkBxExplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBxExplainActionPerformed
    config.setExplain(chkBxExplain.isSelected());
}//GEN-LAST:event_chkBxExplainActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBox1point1;
    private javax.swing.JCheckBox chkBoxIM;
    private javax.swing.JCheckBox chkBoxIT;
    private javax.swing.JCheckBox chkBoxL;
    private javax.swing.JCheckBox chkBoxNOVW;
    private javax.swing.JCheckBox chkBoxT;
    private javax.swing.JCheckBox chkBoxTraceJava;
    private javax.swing.JCheckBox chkBxExplain;
    private javax.swing.JButton doneBtn;
    private javax.swing.JTextField initialModeTextField;
    private javax.swing.JTextField initialTemplateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radioButtonDS;
    private javax.swing.JRadioButton radioButtonDT;
    private javax.swing.JRadioButton radioButtonSALL;
    private javax.swing.JRadioButton radioButtonSIGNORABLE;
    private javax.swing.JRadioButton radioButtonSNONE;
    private javax.swing.JRadioButton radioButtonW0;
    private javax.swing.JRadioButton radioButtonW1;
    private javax.swing.JRadioButton radioButtonW2;
    private javax.swing.JButton switchesRestoreDefaultsBtn;
    private javax.swing.ButtonGroup treeTypeButtonGroup;
    private javax.swing.ButtonGroup warningsButtonGroup;
    private javax.swing.ButtonGroup whitespaceButtonGroup;
    // End of variables declaration//GEN-END:variables
    
}
