package net.sf.kernow.ui;

import net.sf.kernow.ui.util.ComboBoxUtil;
import java.net.URISyntaxException;
import java.util.Properties;
import java.util.ResourceBundle;
import javax.swing.JTabbedPane;
import javax.swing.SwingWorker;
import javax.xml.transform.Source;
import net.sf.kernow.ui.util.DisablingToggleButtonController;
import net.sf.kernow.ui.util.FileComboController;
import net.sf.saxon.s9api.Destination;
import net.sf.saxon.s9api.Serializer;

public class TabSingleFile extends javax.swing.JPanel implements Tab {
    
    private TabbedView view;
    private FileComboController input;
    private FileComboController stylesheet;
    private FileComboController output;
    private DisablingToggleButtonController disablingOutput;
    
    private final int splitPanePos = 220;
    
    private ResourceBundle bundle = ResourceBundle.getBundle("net/sf/kernow/i18n/TabbedView");
    
    /**
     * Creates new form TabSingleFile.
     */
    public TabSingleFile() {
        initComponents();

        // file controllers
        input = new FileComboController(inputCombo, inputButton, false);
        stylesheet = new FileComboController(stylesheetCombo, stylesheetButton, false);
        output = new FileComboController(outputCombo, outputButton, false);

        // disabling controller for the "output" group
        disablingOutput = new DisablingToggleButtonController(sendToFile);
        disablingOutput.add(outputCombo);
        disablingOutput.add(outputButton);
        disablingOutput.add(outputLabel);
    }

    @Override
    public void init(TabbedView view) {
        this.view = view;
    }

    @Override
    public void insertInto(JTabbedPane pane, int pos) {        
        String name = bundle.getString("Single_File");
        String tooltip = bundle.getString("Run_a_stylesheet_against_a_single_file");
        pane.insertTab(name, null, this, tooltip, pos);
    }

    @Override
    public void loadProperties(Properties props) {
        input.loadValues(props, "singleSourceXMLFileCmbBx");
        stylesheet.loadValues(props, "singleStylesheetCmbBx");
        sendToFile.setSelected(Boolean.parseBoolean(props.getProperty("singleSendOutputToFileChkBox", "false")));
        output.loadValues(props, "singleOutputFileCmbBx");
    }
    
    @Override
    public void saveProperties(Properties props) {
        input.saveValues(props, "singleSourceXMLFileCmbBx");
        stylesheet.saveValues(props, "singleStylesheetCmbBx");
        output.saveValues(props, "singleOutputFileCmbBx");
        props.setProperty("singleSendOutputToFileChkBox", Boolean.toString(sendToFile.isSelected()));
    }

    @Override
    public void setRunButtonsEnabled(boolean enable) {
        runButton.setEnabled(enable);
        paramsButton.setEnabled(enable);
        inputButton.setEnabled(enable);
        stylesheetButton.setEnabled(enable);
        if ( sendToFile.isSelected()) {
            outputButton.setEnabled(enable);
        }
    }

    @Override
    public void setAllCaretPositions() {
        ComboBoxUtil.setCaretPosition(inputCombo);
        ComboBoxUtil.setCaretPosition(stylesheetCombo);
        ComboBoxUtil.setCaretPosition(outputCombo);
    }    
    
    @Override
    public int getSplitPanePos() {
        return splitPanePos;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        titleSeparator = new javax.swing.JSeparator();
        inputLabel = new javax.swing.JLabel();
        stylesheetLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        inputCombo = new javax.swing.JComboBox();
        stylesheetCombo = new javax.swing.JComboBox();
        outputCombo = new javax.swing.JComboBox();
        inputButton = new javax.swing.JButton();
        stylesheetButton = new javax.swing.JButton();
        outputButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        paramsButton = new javax.swing.JButton();
        sendToFile = new javax.swing.JCheckBox();

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/TabbedView"); // NOI18N
        titleLabel.setText(bundle.getString("Single_File_Transformation")); // NOI18N

        inputLabel.setText(bundle.getString("XML_File")); // NOI18N

        stylesheetLabel.setText(bundle.getString("Stylesheet")); // NOI18N

        outputLabel.setText(bundle.getString("Output_File")); // NOI18N

        inputCombo.setEditable(true);

        stylesheetCombo.setEditable(true);

        outputCombo.setEditable(true);

        inputButton.setText("...");
        inputButton.setMaximumSize(new java.awt.Dimension(35, 23));
        inputButton.setMinimumSize(new java.awt.Dimension(35, 23));

        stylesheetButton.setText("...");
        stylesheetButton.setMaximumSize(new java.awt.Dimension(35, 23));
        stylesheetButton.setMinimumSize(new java.awt.Dimension(35, 23));

        outputButton.setText("...");
        outputButton.setMaximumSize(new java.awt.Dimension(35, 23));
        outputButton.setMinimumSize(new java.awt.Dimension(35, 23));

        runButton.setText(bundle.getString("Run")); // NOI18N
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        paramsButton.setText(bundle.getString("Params")); // NOI18N
        paramsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramsButtonActionPerformed(evt);
            }
        });

        sendToFile.setText(bundle.getString("Send_output_to_file")); // NOI18N
        sendToFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        sendToFile.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputLabel)
                        .addGap(19, 19, 19)
                        .addComponent(inputCombo, 0, 384, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stylesheetLabel)
                            .addComponent(outputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(outputCombo, 0, 384, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stylesheetCombo, 0, 384, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stylesheetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sendToFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                        .addComponent(paramsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(inputCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stylesheetLabel)
                    .addComponent(stylesheetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stylesheetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputLabel)
                    .addComponent(outputCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton)
                    .addComponent(paramsButton)
                    .addComponent(sendToFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        final SwingWorker worker = new SwingWorker() {
            
            @Override
            public Object doInBackground() {
                
                view.startIndeterminant(bundle.getString("Working..."));
                
                boolean success = false;
                
                try {
                    Source src    = input.getSelectedSource();
                    Source style  = stylesheet.getSelectedSource();

                    Serializer serializer;
                    if (sendToFile.isSelected()) {
                        serializer = output.getSelectedDestination();
                    } else {
                        serializer = new Serializer();
                        serializer.setOutputStream(System.out);
                    }

                    success = view.getTransformController().runSingleFileTransform(src, style, serializer);

                } catch (URISyntaxException e) {
                    System.out.println(e.toString());
                }
                
                view.endIndeterminant(success);
                
                return "SingleFile Transformation Finished";
            }
        };
        
        view.executeService(worker);
    }//GEN-LAST:event_runButtonActionPerformed

    private void paramsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramsButtonActionPerformed
        Object obj = stylesheetCombo.getSelectedItem();
        if (obj != null) {
            view.getParamsDiag().showParamsForStylesheet(obj.toString());
        } else {
            System.err.println("You must select a stylesheet first.");
        }
    }//GEN-LAST:event_paramsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputButton;
    private javax.swing.JComboBox inputCombo;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JButton outputButton;
    private javax.swing.JComboBox outputCombo;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton paramsButton;
    private javax.swing.JButton runButton;
    private javax.swing.JCheckBox sendToFile;
    private javax.swing.JButton stylesheetButton;
    private javax.swing.JComboBox stylesheetCombo;
    private javax.swing.JLabel stylesheetLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JSeparator titleSeparator;
    // End of variables declaration//GEN-END:variables
    
}
