/*
 * About.java
 *
 * Created on 03 October 2005, 13:40
 */

package net.sf.kernow.ui;

import java.awt.Cursor;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import net.sf.kernow.util.BrowserLauncher;

/**
 *
 * @author  AWelch
 */
public class Donate extends javax.swing.JFrame {
    
    /** Creates new form About */
    public Donate() {
        initComponents();
        donateLink.addMouseMotionListener(new MouseMotionListener() {
           public void mouseDragged(MouseEvent e) {
               mouseHand(e);
           }
           public void mouseMoved(MouseEvent e) {
               mouseHand(e);
           }
       });
       
       supportKernowPanel.addMouseMotionListener(new MouseMotionListener() {
           public void mouseDragged(MouseEvent e) {
               mousePointer(e);
           }
           public void mouseMoved(MouseEvent e) {
               mousePointer(e);
           }
       });
    }
    
    public void mouseHand(MouseEvent event) {
       if (!getCursor().equals(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR))) {
           setCursor(new Cursor(Cursor.HAND_CURSOR));
       }
   }
    
    public void mousePointer(MouseEvent event) {
        if (!getCursor().equals(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR))) {
            setCursor(Cursor.getDefaultCursor());
        } 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        supportKernowPanel = new javax.swing.JPanel();
        aboutCloseBtn = new javax.swing.JButton();
        donateLink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/Donate"); // NOI18N
        setTitle(bundle.getString("Support_Kernow")); // NOI18N
        setResizable(false);
        supportKernowPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Support Kernow"));
        aboutCloseBtn.setText(bundle.getString("Close")); // NOI18N
        aboutCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutCloseBtnActionPerformed(evt);
            }
        });

        donateLink.setForeground(new java.awt.Color(0, 0, 255));
        donateLink.setText(bundle.getString("Click_here_to_open_the_SF_donation_page")); // NOI18N
        donateLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectPageClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout supportKernowPanelLayout = new org.jdesktop.layout.GroupLayout(supportKernowPanel);
        supportKernowPanel.setLayout(supportKernowPanelLayout);
        supportKernowPanelLayout.setHorizontalGroup(
            supportKernowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(supportKernowPanelLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .add(aboutCloseBtn))
            .add(supportKernowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(donateLink)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        supportKernowPanelLayout.setVerticalGroup(
            supportKernowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, supportKernowPanelLayout.createSequentialGroup()
                .add(54, 54, 54)
                .add(donateLink)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 56, Short.MAX_VALUE)
                .add(aboutCloseBtn))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(supportKernowPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(supportKernowPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectPageClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectPageClicked
        BrowserLauncher.openURL("http://sourceforge.net/donate/index.php?group_id=161018");
    }//GEN-LAST:event_projectPageClicked

    private void aboutCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutCloseBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_aboutCloseBtnActionPerformed
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutCloseBtn;
    private javax.swing.JLabel donateLink;
    private javax.swing.JPanel supportKernowPanel;
    // End of variables declaration//GEN-END:variables
    
}
