/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Purchase.java
 *
 * Created on 04-Jan-2011, 14:13:59
 */

package net.sf.kernow.ui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import net.sf.kernow.Config;
import net.sf.kernow.Status;
import net.sf.kernow.util.BrowserLauncher;
import net.sf.kernow.util.PropertyManager;

/**
 *
 * @author andrew
 */
public class Purchase extends javax.swing.JFrame {

    private JFrame tabbedView = null;
    private Config config = null;

    /** Creates new form Purchase */
    public Purchase(JFrame tabbedView) {
        initComponents();

        // set the dialog icon
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage(this.getClass().getClassLoader().getResource("icons/Kernow-Icon.gif")));

        this.config = Config.getConfig();
        this.tabbedView = tabbedView;

        kernowVersion.setText(config.getKernowVersion());
        kernowVersion.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("icons/Kernow-Icon.gif")));

        purchaseLink.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("icons/buy.gif")));


        MouseListener mouseListener = new MouseListener(this, Cursor.HAND_CURSOR);
        emailFreeLicLbl.addMouseMotionListener(mouseListener);
        purchaseLink.addMouseMotionListener(mouseListener);

        if (config.getStatus() == Status.LOCKED) {
            Integer remaining = Config.getConfig().getOps();
            if (remaining < 0) {
                remaining = 0;
            }
            remainingUsesValueLbl.setText(Integer.toString(remaining));
        } else {
            remainingUsesValueLbl.setText("Unlocked");
        }
        
        doUpdate();

        MouseListener generalMouseListener = new MouseListener(this, Cursor.DEFAULT_CURSOR);
        super.addMouseMotionListener(generalMouseListener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeBttn = new javax.swing.JButton();
        remainingUsesLbl = new javax.swing.JLabel();
        remainingUsesValueLbl = new javax.swing.JLabel();
        kernowVersion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        purchaseLink = new javax.swing.JLabel();
        unlockCodeTxtFld = new javax.swing.JTextField();
        unlockBttn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        enterCodeLbl = new javax.swing.JLabel();
        unlockStatusLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailFreeLicLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Kernow");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Purchase Kernow"));

        closeBttn.setText("Close");
        closeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBttnActionPerformed(evt);
            }
        });

        remainingUsesLbl.setText("Remaining uses:");

        remainingUsesValueLbl.setFont(new java.awt.Font("Tahoma", 1, 11));
        remainingUsesValueLbl.setText("100");

        kernowVersion.setFont(new java.awt.Font("Tahoma", 1, 12));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/About"); // NOI18N
        kernowVersion.setText(bundle.getString("About.kernowVersion.text_1")); // NOI18N

        jLabel1.setText("The trial version of Kernow allows you to click the run button 100 times.");

        jLabel3.setText("To unlock Kernow, and to support it's continued development, please use the button below:");

        purchaseLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchaseLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseLinkMouseClicked(evt);
            }
        });

        unlockBttn.setText("Unlock now");
        unlockBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockBttnActionPerformed(evt);
            }
        });

        jLabel4.setText("You will be redirected to a page where you will be given a code to enter in the box below:");

        enterCodeLbl.setText("Enter code:");

        unlockStatusLbl.setText("Locked.");

        jLabel6.setText("Status:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel2.setText("Non-commercial users only.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel5.setText("This may take several days, unlocking is instant.");

        emailFreeLicLbl.setFont(new java.awt.Font("Tahoma", 0, 10));
        emailFreeLicLbl.setForeground(new java.awt.Color(0, 0, 255));
        emailFreeLicLbl.setText("Request a free license.");
        emailFreeLicLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailFreeLicLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(purchaseLink, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kernowVersion)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(remainingUsesLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remainingUsesValueLbl))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                                .addComponent(closeBttn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emailFreeLicLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(enterCodeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unlockCodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unlockBttn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unlockStatusLbl)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kernowVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remainingUsesLbl)
                    .addComponent(remainingUsesValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unlockCodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unlockBttn)
                    .addComponent(enterCodeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(unlockStatusLbl))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(closeBttn)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailFreeLicLbl)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBttnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeBttnActionPerformed

    private void unlockBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockBttnActionPerformed
        String cd = unlockCodeTxtFld.getText();
        byte[] arr = {45,84,104,97,110,107,121,111,117,70,111,114,83,117,112,112,111,114,116,105,110,103,75,101,114,110,111,119,45};
        if (cd.equalsIgnoreCase(new String(arr))) {
            Config.getConfig().setStatus(Status.UNLOCKED);
            PropertyManager.saveProperties(Config.getConfig());
            doUpdate();
        } else {
            unlockStatusLbl.setText("Incorrect code.");
            unlockStatusLbl.setForeground(Color.RED);
        }
    }//GEN-LAST:event_unlockBttnActionPerformed

    private void purchaseLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseLinkMouseClicked
        //BrowserLauncher.openURL("https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=LQAAWQSD6MSXC");        
        BrowserLauncher.openURL("http://andrewjwelch.com/purchase-page.html");
    }//GEN-LAST:event_purchaseLinkMouseClicked

    private void emailFreeLicLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFreeLicLblMouseClicked
        BrowserLauncher.openURL("http://kernowforsaxon.sourceforge.net");
    }//GEN-LAST:event_emailFreeLicLblMouseClicked

    private void doUpdate() {
        if (Config.getConfig().getStatus() == Status.UNLOCKED) {
            unlockStatusLbl.setText("Unlocked!");
            unlockStatusLbl.setForeground(Color.GREEN.darker());
            unlockCodeTxtFld.setEnabled(false);
            unlockBttn.setEnabled(false);
            enterCodeLbl.setEnabled(false);
            tabbedView.setTitle(tabbedView.getTitle().replaceAll(" trial", ""));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBttn;
    private javax.swing.JLabel emailFreeLicLbl;
    private javax.swing.JLabel enterCodeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kernowVersion;
    private javax.swing.JLabel purchaseLink;
    private javax.swing.JLabel remainingUsesLbl;
    private javax.swing.JLabel remainingUsesValueLbl;
    private javax.swing.JButton unlockBttn;
    private javax.swing.JTextField unlockCodeTxtFld;
    private javax.swing.JLabel unlockStatusLbl;
    // End of variables declaration//GEN-END:variables

}
