package net.sf.kernow.ui;

import net.sf.kernow.ui.util.ComboBoxUtil;
import java.util.Properties;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.JTabbedPane;
import javax.swing.SwingWorker;
import net.sf.kernow.ui.util.FileComboController;
import net.sf.kernow.util.AntTargetExtractor;

/**
 *
 * @author  Florent Georges
 */
public class TabAnt extends javax.swing.JPanel implements Tab {
    
    private TabbedView view;
    private FileComboController build;  
    
    private final int splitPanePos = 220;
    
    private ResourceBundle bundle = ResourceBundle.getBundle("net/sf/kernow/i18n/TabbedView");
    
    public TabAnt() {
        initComponents();
        build = new FileComboController(buildCombo, buildButton, false);
    }
    
    @Override
    public void setRunButtonsEnabled(boolean enable) {
        // empty
    }

    @Override
    public void setAllCaretPositions() {
        // empty
    }

    @Override
    public void init(TabbedView view) {
        this.view = view;
    }

    @Override
    public void insertInto(JTabbedPane pane, int pos) {
        pane.insertTab(bundle.getString("Batch"), null, this, bundle.getString("Batch"), pos);
    }
    
    @Override
    public void loadProperties(Properties props) {
        build.loadValues(props, "antBuildFileCmbBx");
        levelCombo.setSelectedIndex(Integer.parseInt(props.getProperty("antMessageLevel", "2")));
    }

    @Override
    public void saveProperties(Properties props) {
        build.saveValues(props, "antBuildFileCmbBx");
        props.setProperty("antMessageLevel", String.valueOf(levelCombo.getSelectedIndex()));
    }

    @Override
    public int getSplitPanePos() {
        return splitPanePos;
    }
    
    private void antPopulateTargets() {
        String file = build.getSelectedString();
        if (file != null) {
            setAntTargetComboBoxEnabled(true);
            Set<String> targets = AntTargetExtractor.getAntTargets(file);
            String      def     = AntTargetExtractor.getDefaultTarget(file);
            setAntTargets(targets, def);
        }
    }
    
    private void setAntTargets(Set<String> targets, String def) {
        targetCombo.removeAllItems();
        if (def == null || "".equals(def)) {
            //System.out.println("No default target found!");
        } else {
            targetCombo.addItem(def);
            // remove the default from the list to prevent it appearing twice
            targets.remove(def);
        }
        if (targets.size() > 0) {
            targetCombo.addItem(" - - - - - - - - ");
            for (String t : targets) {
                targetCombo.addItem(t);
            }
        }
    }
    
    private void setAntTargetComboBoxEnabled(boolean enable) {
        targetLabel.setEnabled(enable);
        targetCombo.setEnabled(enable);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlteLabel = new javax.swing.JLabel();
        titlteSeparator = new javax.swing.JSeparator();
        buildLabel = new javax.swing.JLabel();
        buildCombo = new javax.swing.JComboBox();
        buildButton = new javax.swing.JButton();
        targetLabel = new javax.swing.JLabel();
        targetCombo = new javax.swing.JComboBox();
        levelLabel = new javax.swing.JLabel();
        levelCombo = new javax.swing.JComboBox();
        runButton = new javax.swing.JButton();
        propertiesButton = new javax.swing.JButton();

        titlteLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/kernow/i18n/TabbedView"); // NOI18N
        titlteLabel.setText(bundle.getString("Batch")); // NOI18N

        buildLabel.setText(bundle.getString("Ant_buildfile")); // NOI18N

        buildCombo.setEditable(true);

        buildButton.setText("...");
        buildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildButtonActionPerformed(evt);
            }
        });

        targetLabel.setText(bundle.getString("Target")); // NOI18N

        targetCombo.setEditable(true);

        levelLabel.setText(bundle.getString("Message_Level")); // NOI18N

        levelCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Error", "Warn", "Info", "Verbose", "Debug" }));

        runButton.setText(bundle.getString("Run")); // NOI18N
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        propertiesButton.setText(bundle.getString("Properties")); // NOI18N
        propertiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertiesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titlteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titlteSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buildLabel)
                            .addComponent(targetLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buildCombo, 0, 364, Short.MAX_VALUE))
                            .addComponent(targetCombo, 0, 364, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buildButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(levelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(levelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(propertiesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titlteSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildLabel)
                    .addComponent(buildCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetLabel)
                    .addComponent(targetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertiesButton)
                    .addComponent(runButton)
                    .addComponent(levelLabel))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buildButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildButtonActionPerformed

        antPopulateTargets();
    }//GEN-LAST:event_buildButtonActionPerformed

    private void propertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesButtonActionPerformed
        String file = build.getSelectedString();
        view.getParamsDiag().showPropertiesForBuildfile(file);
    }//GEN-LAST:event_propertiesButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        // Make sure a buildfile and target is specified
        // final String buildFile = helper.getComboBoxValue(buildCombo);
        final String buildFile = build.getSelectedString();
        final String t = ComboBoxUtil.getComboBoxValue(targetCombo);
        final int lvl = levelCombo.getSelectedIndex();
        
        if (buildFile == null) {
            System.out.println(bundle.getString("Buildfile_not_set!"));
            return;
        }
        
        // length > 0 ensures the user hasn't backspaced the value out
        if (t == null || t.length() == 0) {
            System.out.println(bundle.getString("Target_not_set!"));
            return;
        }
        
        final SwingWorker worker = new SwingWorker() {
            public Object doInBackground() {
                
                view.startIndeterminant(bundle.getString("Working..."));
                
                boolean success = false;
                
                try {
                    success = view.getTransformController().runAnt(buildFile, t, lvl);
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                
                view.endIndeterminant(success);
                
                return "standalone transform finished";
            }
        };
        
        view.executeService(worker);
    }//GEN-LAST:event_runButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildButton;
    private javax.swing.JComboBox buildCombo;
    private javax.swing.JLabel buildLabel;
    private javax.swing.JComboBox levelCombo;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton propertiesButton;
    private javax.swing.JButton runButton;
    private javax.swing.JComboBox targetCombo;
    private javax.swing.JLabel targetLabel;
    private javax.swing.JLabel titlteLabel;
    private javax.swing.JSeparator titlteSeparator;
    // End of variables declaration//GEN-END:variables
}
